=== jacfpentester/XML/Actividad2.dtd
<!ELEMENT ticket (datosticket, datoscomercio,datoscompra+)>

<!--DATOS DEL TICKET-->
<!ELEMENT datosticket (fechahora,preciototal,formapago)>
<!ATTLIST datosticket id CDATA  #REQUIRED>

<!ELEMENT fechahora (#PCDATA)>
<!ELEMENT preciototal (preciobase,iva,pvptotal)>
  <!ELEMENT preciobase (#PCDATA)>
  <!ELEMENT iva (#PCDATA)>
  <!ELEMENT pvptotal (#PCDATA)>
  <!ATTLIST pvptotal moneda CDATA "Euros">

<!--FORMA PAGO-->
  <!ELEMENT formapago (efectivo?,tarjeta?)>
    <!ELEMENT efectivo (#PCDATA)>
    <!ELEMENT tarjeta (numerotarjeta?, nombretarjeta?)>
    <!ATTLIST tarjeta tipo CDATA "VISA">
        <!ELEMENT numerotarjeta (#PCDATA)>
        <!ELEMENT nombretarjeta (#PCDATA)>
        
<!--DATOS DEL COMERCIO-->
<!ELEMENT datoscomercio  (nombrecomercio,direccioncomercio,cifcomercio,telefonocomercio)>
<!ELEMENT nombrecomercio (#PCDATA)>
<!ELEMENT direccioncomercio (#PCDATA)>
<!ELEMENT cifcomercio (#PCDATA)>
<!ELEMENT telefonocomercio (#PCDATA)>

<!--DATOS DE COMPRA-->
<!ELEMENT datoscompra (nombrearticulo,cantidadarticulo,preciounitarioarticulo,ivaarticulo,pvparticulo)>
<!ELEMENT nombrearticulo (#PCDATA)>
<!ELEMENT cantidadarticulo (#PCDATA)>
<!ELEMENT preciounitarioarticulo (#PCDATA)>
<!ELEMENT ivaarticulo (#PCDATA)>
<!ELEMENT pvparticulo (#PCDATA)>

=== jacfpentester/XML/Actividad2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ticket SYSTEM "Actividad2.dtd">
<ticket>
  <datosticket id="TICKET0"> <!-- Le agregamos  el prefijo TICKET para poder usar el parametro ID y hacerlo unico-->
  <fechahora>20/10/2020</fechahora>
      <preciototal>
        <preciobase>200€</preciobase>
        <iva>16%</iva>
        <pvptotal  moneda="Euros">232€</pvptotal>
      </preciototal>
      <formapago>
        <efectivo>no</efectivo>
        <tarjeta tipo="VISA">
         <numerotarjeta>4545454568</numerotarjeta>
         <nombretarjeta>Banco General</nombretarjeta>
        </tarjeta>
      </formapago>
  </datosticket>
  
  <datoscomercio>
    <nombrecomercio>Centro Comercial Manuel</nombrecomercio>
    <direccioncomercio>Calle Magnolia  num 5</direccioncomercio>
    <cifcomercio>B345623465</cifcomercio>
    <telefonocomercio>53564542</telefonocomercio>
  </datoscomercio>
  
   <datoscompra>
    <nombrearticulo>coche</nombrearticulo>
    <cantidadarticulo>1</cantidadarticulo>
    <preciounitarioarticulo>23€</preciounitarioarticulo>
    <ivaarticulo>16%</ivaarticulo>
    <pvparticulo>31€</pvparticulo>
  </datoscompra>
  
   <datoscompra>
    <nombrearticulo>coche</nombrearticulo>
    <cantidadarticulo>1</cantidadarticulo>
    <preciounitarioarticulo>23€</preciounitarioarticulo>
    <ivaarticulo>16%</ivaarticulo>
    <pvparticulo>31€</pvparticulo>
  </datoscompra>
</ticket>
